server:
  port: 8001
spring:
  profiles:
    active: subversion
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        svn:
          uri: https://youxuehu-PC/svn/config-repo/
          username: youxuehu
          password: zhf123..
          default-label: config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/